In [10]:
import os
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

os.chdir('/Users/fogellmcmuffin/Documents/thesis/_replication/')    # Working dir

mean_spf_trim = pd.read_csv('cleaned_data/mean_spf_trim.csv')
ind_spf_trim = pd.read_csv('cleaned_data/ind_spf_trim.csv')

mean_spf_trim = mean_spf_trim.set_index('DATE')
ind_spf_trim = ind_spf_trim.set_index(['DATE', 'ID'])
ind_spf_trim = ind_spf_trim.drop(['INDUSTRY'], axis=1)

###############################################
                ## SUM STATS ##
###############################################

def sumstats(df, end_date):
    df = df[:end_date]
    df = df.drop(['CPI1', 'CPI2', 'CPI3', 'CPI4', 'CPI5', 'CPI6'], axis=1)
    df = df * 100
    for n in range(0,4):
        df[f'ru_t{n}'] = (df[f'r_t{n}'] > 0).astype(int)
        df[f'rd_t{n}'] = (df[f'r_t{n}'] < 0).astype(int)
        df[f'rn_t{n}'] = (df[f'r_t{n}'] == 0).astype(int)
    return df

ind_stats = sumstats(ind_spf_trim, '2016-12-31')
mean_stats = sumstats(mean_spf_trim, '2016-12-31')

ind_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,3424.0000,3424.0000,3424.0000,3424.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000
mean,0.6525,1.3240,2.0224,2.7435,3.4854,-0.0291,-0.0610,-0.0846,-0.1055,-0.0165,-0.0582,-0.1323,-0.2218,-0.3315,0.3667,0.4346,0.0,0.3440,0.4208,0.0365,0.3389,0.4341,0.0283,0.3424,0.4383,0.0206
std,0.4398,0.7178,0.9978,1.2890,1.6027,0.3722,0.5148,0.6373,0.7559,0.4062,0.7798,1.0529,1.2829,1.5136,0.4820,0.4958,0.0,0.4751,0.4937,0.1876,0.4734,0.4957,0.1659,0.4746,0.4962,0.1420
min,-1.8652,-2.5966,-2.9689,-2.6505,-2.2175,-2.6500,-5.4112,-8.2931,-11.2801,-3.5020,-4.9244,-5.4703,-6.5677,-9.7573,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,0.4500,0.9521,1.4569,1.9884,2.5084,-0.1500,-0.2513,-0.3062,-0.3727,-0.2069,-0.4046,-0.6621,-0.8929,-1.1856,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,0.6500,1.2791,1.9120,2.5488,3.1897,-0.0000,-0.0162,-0.0254,-0.0264,-0.0149,-0.0323,-0.1277,-0.2725,-0.3689,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
75%,0.8500,1.6568,2.4700,3.3152,4.1678,0.1251,0.1759,0.1889,0.2062,0.2068,0.3713,0.4892,0.5162,0.5978,1.0000,1.0000,0.0,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000
max,2.9500,5.8326,9.0076,12.3596,15.8989,2.2250,4.3308,6.3570,8.2963,2.2350,3.3814,3.8011,4.8883,6.2129,1.0000,1.0000,0.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [11]:
mean_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,142.0000,142.0000,142.0000,142.0000,142.0000,141.0000,141.0000,141.0000,141.0000,142.0000,142.0000,142.0000,142.0000,142.0000,142.0000,142.0000,142.0,142.0000,142.0000,142.0,142.0000,142.0000,142.0,142.0000,142.0000,142.0
mean,0.7210,1.4619,2.2329,3.0284,3.8482,-0.0263,-0.0604,-0.0886,-0.1164,-0.0180,-0.0642,-0.1478,-0.2535,-0.3829,0.4437,0.5493,0.0,0.4225,0.5704,0.0,0.4155,0.5775,0.0,0.4014,0.5915,0.0
std,0.3917,0.6754,0.9697,1.2759,1.5963,0.2534,0.3370,0.3975,0.4582,0.3081,0.6438,0.8806,1.0760,1.2829,0.4986,0.4993,0.0,0.4957,0.4968,0.0,0.4946,0.4957,0.0,0.4919,0.4933,0.0
min,-0.6342,-0.3955,-0.0341,0.4337,0.9158,-1.2034,-1.6884,-1.8574,-1.9183,-1.8190,-2.7290,-3.9056,-4.1162,-4.0459,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
25%,0.5175,1.0034,1.5433,2.1166,2.6746,-0.0980,-0.1545,-0.2136,-0.2943,-0.1583,-0.3357,-0.5346,-0.7441,-0.9753,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
50%,0.7150,1.3916,2.0658,2.7107,3.4155,-0.0162,-0.0316,-0.0512,-0.0637,-0.0267,-0.0560,-0.1601,-0.3057,-0.3964,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0
75%,0.8596,1.7069,2.6213,3.5798,4.5853,0.0777,0.0821,0.0980,0.1077,0.1485,0.2834,0.3222,0.2951,0.4696,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0
max,2.3156,4.3252,6.3497,8.3471,10.4006,0.7247,0.9643,1.0781,1.1494,0.6687,1.3703,2.0560,2.6623,2.8875,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0

In [12]:
ind_stats = sumstats(ind_spf_trim, '2019-12-31')
mean_stats = sumstats(mean_spf_trim, '2019-12-31')

ind_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,4699.0000,4699.0000,4699.0000,4699.0000,4699.0000,3787.0000,3787.0000,3787.0000,3787.0000,4699.0000,4699.0000,4699.0000,4699.0000,4699.0000,4699.0000,4699.0000,4699.0,4699.0000,4699.0000,4699.0000,4699.0000,4699.0000,4699.0000,4699.0000,4699.0000,4699.0000
mean,0.6418,1.3033,1.9897,2.6967,3.4231,-0.0280,-0.0574,-0.0790,-0.0983,-0.0155,-0.0605,-0.1418,-0.2290,-0.3394,0.3690,0.4369,0.0,0.3486,0.4209,0.0364,0.3422,0.4352,0.0285,0.3454,0.4399,0.0206
std,0.4248,0.6918,0.9616,1.2430,1.5469,0.3593,0.4949,0.6124,0.7259,0.3943,0.7539,1.0217,1.2387,1.4579,0.4826,0.4961,0.0,0.4766,0.4938,0.1873,0.4745,0.4958,0.1665,0.4755,0.4964,0.1422
min,-1.8652,-2.5966,-2.9689,-2.6505,-2.2175,-2.6500,-5.4112,-8.2931,-11.2801,-3.5020,-4.9244,-5.4703,-6.5677,-9.7573,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,0.4500,0.9517,1.4567,1.9866,2.5080,-0.1500,-0.2275,-0.2909,-0.3530,-0.1970,-0.4061,-0.6558,-0.8744,-1.1375,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,0.6250,1.2539,1.8614,2.4937,3.1128,-0.0000,-0.0124,-0.0254,-0.0257,-0.0123,-0.0376,-0.1365,-0.2707,-0.3706,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
75%,0.8443,1.6308,2.4192,3.2384,4.0387,0.1250,0.1607,0.1778,0.2040,0.1979,0.3505,0.4562,0.4739,0.5121,1.0000,1.0000,0.0,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000
max,2.9500,5.8326,9.0076,12.3596,15.8989,2.2250,4.3308,6.3570,8.2963,2.2350,3.3814,3.8011,4.8883,6.2129,1.0000,1.0000,0.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [13]:
mean_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,154.0000,154.0000,154.0000,154.0000,154.0000,153.0000,153.0000,153.0000,153.0000,154.0000,154.0000,154.0000,154.0000,154.0000,154.0000,154.0000,154.0,154.0000,154.0000,154.0,154.0000,154.0000,154.0,154.0000,154.0000,154.0
mean,0.7064,1.4332,2.1883,2.9658,3.7662,-0.0262,-0.0580,-0.0840,-0.1100,-0.0175,-0.0660,-0.1547,-0.2586,-0.3866,0.4481,0.5455,0.0,0.4286,0.5649,0.0,0.4156,0.5779,0.0,0.4026,0.5909,0.0
std,0.3809,0.6567,0.9441,1.2443,1.5589,0.2456,0.3253,0.3836,0.4424,0.3005,0.6254,0.8592,1.0444,1.2404,0.4989,0.4996,0.0,0.4965,0.4974,0.0,0.4944,0.4955,0.0,0.4920,0.4933,0.0
min,-0.6342,-0.3955,-0.0341,0.4337,0.9158,-1.2034,-1.6884,-1.8574,-1.9183,-1.8190,-2.7290,-3.9056,-4.1162,-4.0459,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
25%,0.4987,1.0025,1.5433,2.1166,2.6746,-0.0980,-0.1485,-0.2070,-0.2631,-0.1504,-0.3357,-0.5346,-0.7441,-0.9562,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
50%,0.6848,1.3476,1.9471,2.5865,3.2208,-0.0149,-0.0285,-0.0461,-0.0599,-0.0223,-0.0594,-0.1601,-0.3057,-0.4017,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0
75%,0.8435,1.6606,2.5912,3.5289,4.5002,0.0777,0.0756,0.0941,0.1077,0.1445,0.2778,0.3186,0.2834,0.2770,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0
max,2.3156,4.3252,6.3497,8.3471,10.4006,0.7247,0.9643,1.0781,1.1494,0.6687,1.3703,2.0560,2.6623,2.8875,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0

In [14]:
ind_stats = sumstats(ind_spf_trim, '2022-12-31')
mean_stats = sumstats(mean_spf_trim, '2022-12-31')

ind_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,4148.0000,4148.0000,4148.0000,4148.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000
mean,0.6598,1.3263,2.0104,2.7132,3.4328,-0.0066,-0.0240,-0.0400,-0.0540,0.0116,0.0174,0.0071,-0.0091,-0.0419,0.3901,0.4218,0.0,0.3715,0.4058,0.0346,0.3645,0.4202,0.0272,0.3674,0.4253,0.0192
std,0.4620,0.7337,0.9997,1.2742,1.5687,0.3969,0.5444,0.6672,0.7854,0.4286,0.8600,1.2250,1.5709,1.9249,0.4878,0.4939,0.0,0.4833,0.4911,0.1829,0.4813,0.4936,0.1627,0.4821,0.4944,0.1372
min,-1.8652,-2.5966,-3.3376,-4.1833,-4.9020,-2.6500,-5.4112,-8.2931,-11.2801,-3.5020,-4.9244,-5.4703,-6.5677,-9.7573,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,0.4500,0.9519,1.4567,1.9865,2.5084,-0.1500,-0.2265,-0.2794,-0.3312,-0.1949,-0.3961,-0.6314,-0.8320,-1.0733,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,0.6500,1.2539,1.8856,2.4979,3.1130,-0.0000,0.0000,-0.0051,-0.0066,-0.0043,-0.0093,-0.0810,-0.1981,-0.2869,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
75%,0.8750,1.6562,2.4446,3.2641,4.0901,0.1566,0.2010,0.2281,0.2559,0.2274,0.4294,0.5733,0.6391,0.7311,1.0000,1.0000,0.0,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000
max,2.9500,5.8326,9.0076,12.3596,15.8989,2.8500,4.3308,6.3570,8.2963,2.6153,4.5848,6.8892,9.0579,11.4740,1.0000,1.0000,0.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [15]:
mean_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,166.0000,166.0000,166.0000,166.0000,166.0000,165.0000,165.0000,165.0000,165.0000,166.0000,166.0000,166.0000,166.0000,166.0000,166.0000,166.0000,166.0,166.0000,166.0000,166.0,166.0000,166.0000,166.0,166.0000,166.0000,166.0
mean,0.7203,1.4479,2.1965,2.9655,3.7547,-0.0084,-0.0301,-0.0513,-0.0723,0.0079,0.0040,-0.0210,-0.0606,-0.1196,0.4759,0.5181,0.0,0.4518,0.5422,0.0,0.4398,0.5542,0.0,0.4277,0.5663,0.0
std,0.4058,0.6759,0.9521,1.2409,1.5437,0.2755,0.3651,0.4261,0.4870,0.3328,0.7292,1.0605,1.3777,1.7073,0.5009,0.5012,0.0,0.4992,0.4997,0.0,0.4979,0.4986,0.0,0.4962,0.4971,0.0
min,-0.6342,-0.3955,-0.0341,0.4337,0.9158,-1.2034,-1.6884,-1.8574,-1.9183,-1.8190,-2.7290,-3.9056,-4.1162,-4.0459,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
25%,0.4987,1.0025,1.5381,2.1123,2.6643,-0.0901,-0.1382,-0.2062,-0.2440,-0.1504,-0.3237,-0.5194,-0.7306,-0.9206,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
50%,0.6896,1.3567,1.9627,2.6034,3.2431,-0.0101,-0.0174,-0.0337,-0.0413,-0.0191,-0.0478,-0.1343,-0.2838,-0.3915,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0
75%,0.8596,1.7069,2.6152,3.5425,4.5194,0.1017,0.1064,0.1351,0.1448,0.1661,0.3752,0.4417,0.4398,0.5870,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0
max,2.3156,4.3252,6.3497,8.3471,10.4006,0.8784,1.2717,1.4820,1.6548,1.2066,2.4983,4.1459,5.3931,7.4276,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0