In [45]:
import os
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

os.chdir('/Users/fogellmcmuffin/Documents/thesis/_replication/')    # Working dir

mean_spf_trim = pd.read_csv('cleaned_data/mean_spf_trim.csv')
ind_spf_trim = pd.read_csv('cleaned_data/ind_spf_trim.csv')

mean_spf_trim = mean_spf_trim.set_index('DATE')
ind_spf_trim = ind_spf_trim.set_index(['DATE', 'ID'])
ind_spf_trim = ind_spf_trim.drop(['INDUSTRY'], axis=1)

###############################################
                ## SUM STATS ##
###############################################

def sumstats(df, end_date):
    df = df[:end_date]
    df = df.drop(['CPI1', 'CPI2', 'CPI3', 'CPI4', 'CPI5', 'CPI6'], axis=1)
    df = df * 100
    for n in range(0,4):
        df[f'ru_t{n}'] = (df[f'r_t{n}'] > 0).astype(int)
        df[f'rd_t{n}'] = (df[f'r_t{n}'] < 0).astype(int)
        df[f'rn_t{n}'] = (df[f'r_t{n}'] == 0).astype(int)
    return df

ind_stats = sumstats(ind_spf_trim, '2016-12-31')
mean_stats = sumstats(mean_spf_trim, '2016-12-31')

ind_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,3424.0000,3424.0000,3424.0000,3424.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000,4273.0000
mean,0.6537,1.3271,2.0260,2.7477,3.4895,-0.0292,-0.0596,-0.0831,-0.1036,-0.0177,-0.0612,-0.1358,-0.2260,-0.3356,0.3658,0.4355,0.0,0.3405,0.4269,0.0339,0.3372,0.4388,0.0253,0.3410,0.4421,0.0183
std,0.4314,0.7016,0.9767,1.2638,1.5709,0.3590,0.4920,0.6056,0.7149,0.3968,0.7645,1.0334,1.2581,1.4796,0.4817,0.4959,0.0,0.4739,0.4947,0.1811,0.4728,0.4963,0.1570,0.4741,0.4967,0.1339
min,-1.8250,-2.3799,-2.7460,-2.4056,-1.9715,-2.6500,-5.3340,-8.1077,-10.9525,-3.3770,-4.6973,-5.1456,-6.3251,-9.3923,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,0.4641,0.9522,1.4570,1.9896,2.5250,-0.1500,-0.2285,-0.3046,-0.3576,-0.2002,-0.4001,-0.6539,-0.8868,-1.1707,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,0.6500,1.2791,1.9120,2.5407,3.1897,-0.0000,-0.0251,-0.0255,-0.0499,-0.0150,-0.0323,-0.1233,-0.2729,-0.3760,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
75%,0.8500,1.6416,2.4699,3.2898,4.1676,0.1250,0.1601,0.1779,0.2043,0.2045,0.3614,0.4751,0.5103,0.5744,1.0000,1.0000,0.0,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000
max,2.9500,5.8069,8.9018,12.1416,15.5339,2.2250,4.2398,6.1558,8.0411,2.2350,3.3814,3.8011,4.8156,6.2129,1.0000,1.0000,0.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [46]:
mean_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,142.0000,142.0000,142.0000,142.0000,142.0000,141.0000,141.0000,141.0000,141.0000,142.0000,142.0000,142.0000,142.0000,142.0000,142.0000,142.0000,142.0,142.0000,142.0000,142.0,142.0000,142.0000,142.0,142.0000,142.0000,142.0
mean,0.7221,1.4649,2.2363,3.0323,3.8521,-0.0270,-0.0597,-0.0881,-0.1151,-0.0191,-0.0671,-0.1511,-0.2575,-0.3868,0.4366,0.5563,0.0,0.4085,0.5845,0.0,0.4085,0.5845,0.0,0.4155,0.5775,0.0
std,0.3920,0.6758,0.9691,1.2744,1.5945,0.2541,0.3382,0.3982,0.4572,0.3082,0.6444,0.8814,1.0752,1.2806,0.4977,0.4986,0.0,0.4933,0.4946,0.0,0.4933,0.4946,0.0,0.4946,0.4957,0.0
min,-0.6454,-0.4117,-0.0383,0.4446,0.9213,-1.2160,-1.7074,-1.8806,-1.9386,-1.8152,-2.7230,-3.9096,-4.1203,-4.1103,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
25%,0.5199,1.0042,1.5419,2.1387,2.6840,-0.1023,-0.1584,-0.2210,-0.2794,-0.1586,-0.3383,-0.5360,-0.7431,-0.9851,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
50%,0.7139,1.3997,2.0616,2.7110,3.4230,-0.0173,-0.0322,-0.0525,-0.0583,-0.0263,-0.0557,-0.1664,-0.3089,-0.4046,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0
75%,0.8574,1.7122,2.6185,3.5839,4.5841,0.0780,0.0733,0.0928,0.1066,0.1478,0.2876,0.3313,0.2832,0.4400,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0
max,2.3156,4.3252,6.3497,8.3471,10.4006,0.7187,0.9716,1.0745,1.1457,0.6799,1.3821,2.0571,2.6480,2.8785,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0

In [47]:
ind_stats = sumstats(ind_spf_trim, '2022-12-31')
mean_stats = sumstats(mean_spf_trim, '2022-12-31')

ind_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,4148.0000,4148.0000,4148.0000,4148.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000,5109.0000
mean,0.6612,1.3303,2.0155,2.7188,3.4380,-0.0071,-0.0228,-0.0380,-0.0514,0.0101,0.0134,0.0021,-0.0147,-0.0472,0.3885,0.4234,0.0,0.3692,0.4112,0.0315,0.3633,0.4247,0.0239,0.3672,0.4279,0.0168
std,0.4525,0.7148,0.9734,1.2423,1.5291,0.3798,0.5180,0.6294,0.7349,0.4170,0.8399,1.1998,1.5420,1.8895,0.4875,0.4941,0.0,0.4826,0.4921,0.1747,0.4810,0.4944,0.1527,0.4821,0.4948,0.1287
min,-1.8250,-2.3799,-2.7460,-2.4056,-1.9715,-2.6500,-5.3340,-8.1077,-10.9525,-3.3770,-4.6973,-5.1456,-6.3251,-9.3923,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
25%,0.4501,0.9522,1.4570,1.9896,2.5250,-0.1500,-0.2261,-0.2783,-0.3261,-0.1923,-0.3922,-0.6217,-0.8253,-1.0565,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
50%,0.6500,1.2619,1.8737,2.4978,3.1130,-0.0000,-0.0000,-0.0208,-0.0233,-0.0054,-0.0097,-0.0781,-0.1986,-0.2881,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
75%,0.8750,1.6316,2.4446,3.2386,4.0645,0.1500,0.1998,0.2269,0.2538,0.2243,0.4203,0.5616,0.6272,0.7126,1.0000,1.0000,0.0,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000,1.0000,1.0000,0.0000
max,2.9500,5.8069,8.9018,12.1416,15.5339,2.2250,4.2398,6.1558,8.0411,2.2350,3.3870,5.3447,6.9482,8.4459,1.0000,1.0000,0.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [48]:
mean_stats.describe().round(4)

,f_t0,f_t1,f_t2,f_t3,f_t4,r_t0,r_t1,r_t2,r_t3,e_t0,e_t1,e_t2,e_t3,e_t4,ru_t0,rd_t0,rn_t0,ru_t1,rd_t1,rn_t1,ru_t2,rd_t2,rn_t2,ru_t3,rd_t3,rn_t3
count,166.0000,166.0000,166.0000,166.0000,166.0000,165.0000,165.0000,165.0000,165.0000,166.0000,166.0000,166.0000,166.0000,166.0000,166.0000,166.0000,166.0,166.0000,166.0000,166.0,166.0000,166.0000,166.0,166.0000,166.0000,166.0
mean,0.7217,1.4519,2.2014,2.9709,3.7598,-0.0095,-0.0295,-0.0504,-0.0705,0.0065,0.0000,-0.0259,-0.0660,-0.1247,0.4699,0.5241,0.0,0.4458,0.5482,0.0,0.4337,0.5602,0.0,0.4398,0.5542,0.0
std,0.4068,0.6782,0.9532,1.2405,1.5424,0.2754,0.3664,0.4276,0.4868,0.3324,0.7275,1.0580,1.3743,1.7029,0.5006,0.5009,0.0,0.4986,0.4992,0.0,0.4971,0.4979,0.0,0.4979,0.4986,0.0
min,-0.6454,-0.4117,-0.0383,0.4446,0.9213,-1.2160,-1.7074,-1.8806,-1.9386,-1.8152,-2.7230,-3.9096,-4.1203,-4.1103,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
25%,0.5001,1.0024,1.5370,2.1175,2.6746,-0.0903,-0.1310,-0.2073,-0.2577,-0.1570,-0.3383,-0.5121,-0.7292,-0.9214,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0,0.0000,0.0000,0.0
50%,0.6901,1.3576,1.9725,2.6145,3.2616,-0.0079,-0.0203,-0.0341,-0.0454,-0.0183,-0.0495,-0.1440,-0.2875,-0.3973,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0,0.0000,1.0000,0.0
75%,0.8574,1.7122,2.6164,3.5340,4.5042,0.1122,0.1098,0.1397,0.1596,0.1637,0.3753,0.4409,0.4435,0.5969,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0
max,2.3156,4.3252,6.3497,8.3471,10.4006,0.8570,1.2993,1.5253,1.6974,1.2028,2.4673,4.0785,5.3876,7.4458,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0,1.0000,1.0000,0.0